
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.alexscaves]
			pewen = true
			thornwood = true

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.leaves_type]

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			snowblossom = true
			rainbow_birch = true
			yellow_autumn = true
			orange_autumn = true
			maple = true
			fir = true
			redwood = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.mcwfurnitures]
			wardrobe = true
			stripped_glass_table = true
			stripped_desk = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			end_table = true
			stool_chair = true
			drawer = true
			stripped_lower_triple_drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			chair = true
			stripped_table = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			double_drawer_counter = true
			stripped_striped_chair = true
			covered_desk = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			desk = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_double_wardrobe = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer = true
			stripped_double_drawer_counter = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			double_wardrobe = true
			stripped_drawer = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true

		[entries.wood_type.functionalstorage]
			1 = true
			4 = true
			2 = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.quark]
			vertical_planks = true
			chest = true
			ladder = true
			hollow_log = true
			post = true
			trapped_chest = true
			bookshelf = true
			stripped_post = true
			vertical_slab = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

